### 1. Numpy N-Dimensional Array

In [1]:
import numpy as np

- 주로 숫자형 데이터를 다룰 때 편리
- 속도가 빠르다.
- 같은 데이터 자료형으로 만들어야 한다.
- 내부적으로는 C로 만들었다.

- ndarry와 list의 차이

In [2]:
l = [1, 2, 3, 4, 5]
l = [ i * i for i in l]
l

[1, 4, 9, 16, 25]

In [3]:
n = np.array([1,2,3,4,5], dtype=int)
n

array([1, 2, 3, 4, 5])

In [4]:
n = np.square(n)
n

array([ 1,  4,  9, 16, 25], dtype=int32)

- 1차원 배열(vector)

In [5]:
a = np.array((1,2,3,4,5,6,7,8,9,10))
print(type(a))

<class 'numpy.ndarray'>


In [6]:
# 자료형, 모양, 몇차원인지, 모든 요소개수
a.dtype, a.shape, a.ndim, a.size

(dtype('int32'), (10,), 1, 10)

In [7]:
# 벡터화 연산 
# 각각의 요소에서 * 2 (두배)해준다.
a * 2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [8]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])
c = 2 * a + b
c

array([12, 24, 36])

In [9]:
a == 2, b > 10

(array([False,  True, False]), array([False,  True,  True]))

- 2차원 배열(Matrix)

In [10]:
c = np.array([[1,2,3], [4,5,6]])  # np.arange(1, 7).reshape(2, 3)
print(c)

[[1 2 3]
 [4 5 6]]


In [11]:
c.dtype, c.shape, c.ndim, c.size

(dtype('int32'), (2, 3), 2, 6)

- 3차원 배열(Tensor)

In [12]:
t = np.arange(1, 25).reshape(2, 3, 4)
t

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

- 배열의 인덱싱

In [13]:
a[0], a[1], a[2]

(1, 2, 3)

In [14]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
c[0,0], c[-1,0], c[1,2]

(1, 4, 6)

- 배열 슬라이싱

In [16]:
l = [[1,2,3], [4,5,6],[7,8,9]]
l[:2]

[[1, 2, 3], [4, 5, 6]]

In [17]:
# 리스트에서는 행과 열로 동시에 슬라이싱이 안된다.
l[:2][1:]

[[4, 5, 6]]

In [18]:
c = np.arange(1, 10).reshape(3, 3)
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
# 위의 두 행
c[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
# 오른쪽 두 열
c[:, 1:]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [21]:
c[:][1:]

array([[4, 5, 6],
       [7, 8, 9]])

In [22]:
# 5, 6, 8, 9
c[1:, 1:]

array([[5, 6],
       [8, 9]])

In [23]:
# 1, 4, 3, 6
c[:-1, ::2]

array([[1, 3],
       [4, 6]])

In [24]:
# 1, 7, 3, 9
c[::2, ::2]

array([[1, 3],
       [7, 9]])

In [25]:
m = np.array([[0, 1, 2, 3, 4],
              [5, 6, 7, 8, 9],
              [10, 11, 12, 13, 14]])
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [26]:
print(m[1, 2], m[-1, -1], m[1, 1:3], m[1:, 2], m[:-1, -2:], sep='\n')

7
14
[6 7]
[ 7 12]
[[3 4]
 [8 9]]


- 배열 인덱싱 (Fancy indexing)

In [27]:
a = np.array([1,2,3,4,5,6,7,8,9,10])
idex = np.array([True, False, True, False, True, False, True, False, True, False])
a[idex]

array([1, 3, 5, 7, 9])

In [28]:
a % 2 == 1

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [29]:
a[a % 2 == 1]

array([1, 3, 5, 7, 9])

In [30]:
# idx 값이 정수값(인덱스)이면 해당 인덱스의 원소가 선택됨
idx = np.array([1, 3, 5, 7, 9])
a[idx]

array([ 2,  4,  6,  8, 10])

In [31]:
x = np.array([1,2,3,4,5,6,7,8,9,10,
              11,12, 13, 14, 15, 16, 17, 18, 19, 20])

# 3의 배수
x[x % 3 == 0]

array([ 3,  6,  9, 12, 15, 18])

In [32]:
# 4로 나누어서 1이 남는 수
x[x % 4 == 1]

array([ 1,  5,  9, 13, 17])

In [33]:
# 3으로 나누면 나누어지고, 4로 나누면 1이 남는 수
x[ (x % 3 == 0) & (x % 4 == 1)]

array([9])

In [34]:
# 위에서 구한 결과는 ndarray임. 원소의 벨류를 끄집어 내려면 다시 인덱싱 해줘야 함
x[8], x[ (x % 3 == 0) & (x % 4 == 1)][0]

(9, 9)