### 3. 배열의 연산(Operation)

In [4]:
import numpy as np

- 벡터화 연산

In [5]:
x = np.arange(1, 101)
y = np.arange(1101, 1201)
z = x + y
z[:5]

array([1102, 1104, 1106, 1108, 1110])

In [6]:
z = 3 * x
z[:5]

array([ 3,  6,  9, 12, 15])

In [7]:
a = np.array([1,2,3,4])
b = np.array([4,2,2,4])
a == b

array([False,  True, False,  True])

In [8]:
a > b

array([False, False,  True, False])

In [9]:
a / b

array([0.25, 1.  , 1.5 , 1.  ])

In [10]:
np.log(a), np.exp(a)

(array([0.        , 0.69314718, 1.09861229, 1.38629436]),
 array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003]))

In [11]:
c = np.arange(6).reshape(2,3)
np.exp(c)

array([[  1.        ,   2.71828183,   7.3890561 ],
       [ 20.08553692,  54.59815003, 148.4131591 ]])

In [12]:
c + 3

array([[3, 4, 5],
       [6, 7, 8]])

- 차원 축소 연산

In [13]:
x = np.arange(1, 5)
np.sum(x)   # 넘파이 함수

10

In [14]:
x.sum()     # 넘파이 객체의 메소드

10

In [15]:
x.min(), x.max() # 최고, 최대

(1, 4)

In [16]:
# 대표값: 평균, 중앙값(mediaum), 
x.mean(), np.median(x)

(2.5, 2.5)

- all or  any

In [17]:
np.all([True, True, True]) # 모든 원소가 참이냐?

True

In [18]:
np.any([True, False, True]) # 하나라도 참인 원소가 있느냐?

True

- 2차원 이상의 연산

In [19]:
a = np.arange(1, 7).reshape(2,3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:

#모든 원소의 합/평균
np.sum(a), np.mean(a)

(21, 3.5)

In [21]:
# 행 방향으로 합/평균
np.sum(a, axis=0), np.mean(a, axis=0)

(array([5, 7, 9]), array([2.5, 3.5, 4.5]))

In [22]:
# 열 방향으로 합/평균
np.sum(a, axis=1), np.mean(a, axis=1)

(array([ 6, 15]), array([2., 5.]))

- argmax, argmin

In [23]:
# index
x = np.array([3, 12, 33, 9, 51, 26])
np.argmax(x), np.argmin(x)

(4, 0)

In [24]:
y = x.reshape(2, 3)
np.argmax(y, axis=0), np.argmin(y, axis=0)

(array([1, 1, 0], dtype=int64), array([0, 0, 1], dtype=int64))

In [25]:
# ex = np.arange(1, 31).reshape(5, 6).astype(float)
ex = np.arange(1, 31, dtype=float).reshape(5, 6)
ex


array([[ 1.,  2.,  3.,  4.,  5.,  6.],
       [ 7.,  8.,  9., 10., 11., 12.],
       [13., 14., 15., 16., 17., 18.],
       [19., 20., 21., 22., 23., 24.],
       [25., 26., 27., 28., 29., 30.]])

In [26]:
np.random.seed(2023)
np.set_printoptions(precision=4, suppress=True)
ex = np.random.random(30).reshape(5, 6)
ex

array([[0.322 , 0.8904, 0.5881, 0.1266, 0.1413, 0.4679],
       [0.0221, 0.7273, 0.5244, 0.5449, 0.4564, 0.5014],
       [0.3945, 0.1512, 0.3609, 0.1621, 0.338 , 0.1803],
       [0.391 , 0.0356, 0.5649, 0.2035, 0.3206, 0.3766],
       [0.1841, 0.104 , 0.4549, 0.1959, 0.3785, 0.9305]])

In [27]:
# 전체의 최대값
np.round(ex.max(), 4)

0.9305

In [28]:
# 각 행의 합
np.sum(ex, axis=1)

array([2.5363, 2.7764, 1.5869, 1.8921, 2.2479])

In [29]:
# 각 행의 최대값
np.max(ex, axis=1)

array([0.8904, 0.7273, 0.3945, 0.5649, 0.9305])

In [30]:
# 각 열의 평균
np.mean(ex, axis=0)

array([0.2627, 0.3817, 0.4986, 0.2466, 0.327 , 0.4913])

In [31]:
# 각 열의 최소값
np.min(ex, axis=0)

array([0.0221, 0.0356, 0.3609, 0.1266, 0.1413, 0.1803])

In [32]:
arr = np.array([[1, 2, 3, 4], 
             [46, 99, 100, 71],
             [81, 59, 90, 100]])
arr

array([[  1,   2,   3,   4],
       [ 46,  99, 100,  71],
       [ 81,  59,  90, 100]])

- 정렬

In [35]:
a = np.array([[4, 3, 5, 7],
              [1, 12, 11, 9],
              [2, 15, 1, 14]])
a

array([[ 4,  3,  5,  7],
       [ 1, 12, 11,  9],
       [ 2, 15,  1, 14]])

In [36]:
np.sort(a)      # axist=1 이 default

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])

In [38]:
np.sort(a, axis=0)

array([[ 1,  3,  1,  7],
       [ 2, 12,  5,  9],
       [ 4, 15, 11, 14]])

In [42]:
# sort()는 자기 파괴적(in-place) method
a.sort()
a

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])

In [47]:
a = np.array([[4, 3, 5, 7],
              [1, 12, 11, 9],
              [2, 15, 1, 14]])
a

array([[ 4,  3,  5,  7],
       [ 1, 12, 11,  9],
       [ 2, 15,  1, 14]])

In [48]:
j = np.argsort(a)
j

array([[1, 0, 2, 3],
       [0, 3, 2, 1],
       [2, 0, 3, 1]], dtype=int64)

In [62]:
# 내림차순 정렬(열 방향)
np.sort(a)[:, ::-1]


array([[ 7,  5,  4,  3],
       [12, 11,  9,  1],
       [15, 14,  2,  1]])

In [66]:
# 내림차순 정렬(행 방향)
np.sort(a, axis=0)[::-1] # [::-1, :]

array([[ 4, 15, 11, 14],
       [ 2, 12,  5,  9],
       [ 1,  3,  1,  7]])

In [67]:
x = np.array([[1,  2,   3,   4],
              [46, 99, 100, 71],
              [81, 59, 90, 100]])

In [69]:
# 영어 성적을 argsort() 하여 인덱스를 구함
x_index = np.argsort(x[1])[::-1]
x_index

array([2, 1, 3, 0], dtype=int64)

In [74]:
# 모든 행을 영어성적 내림차순 기준으로 정렬
x[:, x_index]

array([[  3,   2,   4,   1],
       [100,  99,  71,  46],
       [ 90,  59, 100,  81]])

In [75]:
# 한 줄로
x[:, np.argsort(x[1])[::-1]]


array([[  3,   2,   4,   1],
       [100,  99,  71,  46],
       [ 90,  59, 100,  81]])

In [76]:
a = np.array([[0, 1, 2, 3], 
              [4, 5, 6, 7],
              [8, 9, 10,11]])

In [84]:
a[0], a[:, 1], a[1, ::-1], a[:, 1][::-1]

(array([0, 1, 2, 3]), array([1, 5, 9]), array([7, 6, 5, 4]), array([9, 5, 1]))

In [85]:
# index 배열로 슬라이싱 가능하다
a[:, [3, 1, 0, 2]]  

array([[ 3,  1,  0,  2],
       [ 7,  5,  4,  6],
       [11,  9,  8, 10]])

In [81]:
x = np.array([[1,  2,   3,   4],
              [46, 99, 100, 71],
              [81, 59, 90, 100]])

In [83]:
x[:, np.argsort(x[1])[::-1]]

array([[  3,   2,   4,   1],
       [100,  99,  71,  46],
       [ 90,  59, 100,  81]])