### 5. 난수 발생과 카운팅

In [2]:
import numpy as np

- Seed 설정

In [4]:
np.random.seed(2023)
np.random.random(5)

array([0.3219883 , 0.89042245, 0.58805226, 0.12659609, 0.14134122])

- 데이터의 순서 바꾸기

In [6]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.random.shuffle(x)
x

array([7, 4, 3, 2, 8, 9, 1, 6, 0, 5])

- 데이터 샘플링

In [8]:
np.random.choice(5, 5, replace=False)

array([3, 4, 0, 2, 1])

In [10]:
x = np.random.randint(1, 100, 10)
x

array([71, 16, 89, 73, 48, 66, 72, 23, 54,  8])

In [11]:
np.random.choice(x, 5, replace=False)

array([54,  8, 23, 72, 73])

- 난수 생성

In [12]:
# random() - Uniform 분포 : 균등하게 분포 - ~ 1 사이의 값
np.random.random(10)

array([0.59310305, 0.9147945 , 0.25066314, 0.07173657, 0.30121014,
       0.26788935, 0.72442186, 0.4034967 , 0.47762815, 0.21232418])

In [13]:
# randint(low, high, N) - [low, high)  
np.random.randint(1, 7, 10)

array([4, 6, 2, 4, 5, 4, 6, 6, 2, 5])

In [14]:
# normal(평균, 표준편차, N)
np.random.normal(170, 10, 10)

array([157.48804459, 166.55865928, 180.86199825, 172.62609705,
       169.99914394, 177.58645897, 167.26943945, 147.39058082,
       172.02856304, 170.06243698])

In [15]:
# randn(N) - 표준정규분포 N(0, 1)
np.random.randn(10)

array([-0.69789635,  1.3179999 , -1.3305147 ,  1.84333885,  0.07586461,
       -0.88877486,  0.72900879,  0.17879745,  0.79162212, -0.51695485])

In [16]:
# binomial(시도횟수, 평균, N) - 이항분포 B(N, p)
np.random.binomial(10, 0.5, 20).reshape(4, 5)

array([[5, 2, 4, 5, 2],
       [6, 4, 6, 6, 4],
       [6, 5, 7, 5, 5],
       [5, 6, 3, 6, 7]])

In [17]:
# 가설 검정: t - 검정
# standard_t(자유도, N)
np.random.standard_t(2, 10)

array([ 2.6474858 ,  0.11196557,  2.47395645, -1.38920435, -0.87036697,
        0.37764753, -1.24874601, -0.56429419, -1.74308619, -0.00891616])

In [18]:
# 동전을 10번 던져 앞면(숫자 1)과 뒷면(숫자 0)이 나오는 가상 실험을 파이썬으로 작성한다.
np.random.binomial(1, 0.5, 10)

array([0, 0, 0, 1, 1, 0, 1, 0, 1, 1])

In [20]:
# 주사위를 100번 던져서 나오는 숫자의 평균을 구하라.
np.random.randint(1, 7, 100).mean()

3.62

In [40]:
# 가격이 10,000원인 주식. 일간 수익률(%)은 기댓값이 0%이고 표준편차가 1%인
# 표준 정규 분포를 따른다고 하자. 250일 동안의 주가를 무작위로 생성하라

rate_x = np.random.normal(0, 0.01, 250)


In [47]:
price = 10000
stock = np.zeros_like(rate_x, dtype=int)

for index, val in enumerate(rate_x):
    price = price * ( 1 + val ) 
    stock[index] = price

# print(stock)

In [48]:
# list로 해결
np.random.seed(2023)
rate = np.random.normal(0, 0.01, 250)
rate[:5]

array([ 0.00711674, -0.00324485, -0.01001871,  0.00236251, -0.0010216 ])

In [53]:
# 1. 리스트로 해결
price = 10000
price_list = []
for i in range(250):
    price = price * ( 1 + rate[i])
    price = int(np.round(price))
    price_list.append(price)

price_array = np.array(price_list)
price_array[-10:]

array([10814, 10893, 10674, 10645, 10588, 10724, 10739, 10686, 10691,
       10497])

In [54]:
# 2. numpy array로
price = 10000
price_array2 = np.zeros_like(rate, dtype=int)

for i in range(rate.size):
    price = price * (1 + rate[i])
    price_array2[i] = price

price_array2[-10:]


array([10815, 10894, 10674, 10645, 10588, 10724, 10739, 10686, 10691,
       10497])

- 데이터 카운팅

In [55]:
dices = np.random.randint(1, 7, 100)
np.unique(dices)

array([1, 2, 3, 4, 5, 6])

In [57]:
indices, count = np.unique(dices, return_counts=True)
indices, count

(array([1, 2, 3, 4, 5, 6]), array([ 9, 24, 24, 13, 15, 15], dtype=int64))

In [65]:
# 평균
np.sum(indices * count) / np.sum(count)

3.46

In [66]:
np.mean(dices)

3.46

In [68]:
a = np.array(['a', 'b', 'b', 'c', 'a'])
index, count = np.unique(a, return_counts=True)
index, count

(array(['a', 'b', 'c'], dtype='<U1'), array([2, 2, 1], dtype=int64))

In [ ]:
np.bincount(dices, minlength=6)